site_name: NoteBook
nav:
    - Home: index.md
    - English Grammar:
        - 'Verb': 'english_grammar/verb.md'
        - 'Model verb': 'english_grammar/model_verb.md'
        - 'Preposition': 'english_grammar/preposition.md'
    - Linux:
        - 'Timer': 'linux/timer.md'
theme: readthedocs
